name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile with Maven
      run: mvn compile
    - name: Testing
      run: mvn test
    - name: package
      run: mvn package
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/java-project-1.0-SNAPSHOT.jar
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: 0.0.1
